<?php

namespace AppBundle\Repository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForList(){
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')->addOrderBy('b.published_at','DESC');
        return $qb->getQuery()->getResult();
    }
    public function findBlogPostPublished()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')->where('b.published_at IS NOT NULL');
        return $qb->getQuery()->getResult();
    }
    public function findBlogPostNotPublished()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')->where('b.published_at IS NULL');
        return $qb->getQuery()->getResult();
    }
}
